# Site settings
title: Mauro Rodriguez Jr., PhD
email: mrdz@caltech.edu
description: Academic webpage of Mauro Rodriguez Jr., PhD
baseurl: ""
url: ""
affiliation: >
    I am part of the <a href="http://www.eas.caltech.edu/" target="_blank">Division of Engineering and Applied Science</a> 
    at the California Institute of Technology

# Google analytics ID
#google_analytics: UA-167467135-1

# Location info. (shown in footer)
location: >
  Office: <br/>
  <a href="http://www.mce.caltech.edu/about/gates_thomas" target="_blank">Gates-Thomas Laboratory</a> <br/>
  California Institute of Technology <br/>
  1200 E California Blvd<br/>
  Pasadena, CA 91125, MC104-44

# Contact info. (shown in footer)
contact: >
    <a href="mailto:mrdz@caltech.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Mauro via email</a> <br/>

#####<a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: teaching
  - name: publications
  - name: talks
#  - name: software
# - name: team

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
